# -*- coding: utf-8 -*-
"""Generate Q8 sin/cos ROM tables for 0..359 degrees (matches reference scale 256)."""
import math
from pathlib import Path

out_dir = Path(r"D:\Software\Xiaomi_MiMo\video\zynq_video_pipeline\rtl\process\rotate")
out_dir.mkdir(parents=True, exist_ok=True)

def emit(path, name, values, comment):
    lines = [
        "`timescale 1ns/1ps",
        f"// {comment}",
        f"// Auto-generated by scripts/gen_sin_cos.py — Q8, sin(0)=0, cos(0)=256",
        f"module {name} (",
        "    input  wire [8:0] angle, // 0..359",
        "    output reg signed [9:0] value",
        ");",
        "    always @(*) begin",
        "        case (angle)",
    ]
    for a, v in values:
        lines.append(f"            9'd{a}: value = 10'sd{v};")
    lines += [
        "            default: value = 10'sd0;",
        "        endcase",
        "    end",
        "endmodule",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", path, "entries", len(values))

sin_vals = [(a, int(round(math.sin(math.radians(a)) * 256))) for a in range(360)]
cos_vals = [(a, int(round(math.cos(math.radians(a)) * 256))) for a in range(360)]
# clamp to signed 10-bit (-512..511); 256 fits
emit(out_dir / "sin_rom.v", "sin_rom", sin_vals, "sin(angle)*256")
emit(out_dir / "cos_rom.v", "cos_rom", cos_vals, "cos(angle)*256")

# self-check vs reference
for a in (0, 45, 90, 180, 270, 359):
    s = int(round(math.sin(math.radians(a)) * 256))
    c = int(round(math.cos(math.radians(a)) * 256))
    print(f"angle {a:3d}: sin={s:4d} cos={c:4d}")
